package QuanLy;
// Generated Jun 19, 2020, 2:16:51 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * LoginAdmin generated by hbm2java
 */
@Entity
@Table(name = "login_admin", catalog = "quanlyhs")
public class LoginAdmin implements java.io.Serializable {

	private LoginAdminId id;

	public LoginAdmin() {
	}

	public LoginAdmin(LoginAdminId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "username", column = @Column(name = "username", nullable = false)),
			@AttributeOverride(name = "pass", column = @Column(name = "pass", nullable = false)) })
	public LoginAdminId getId() {
		return this.id;
	}

	public void setId(LoginAdminId id) {
		this.id = id;
	}

}
