package QuanLy;
// Generated Jun 19, 2020, 2:16:51 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * LoginStudent generated by hbm2java
 */
@Entity
@Table(name = "login_student", catalog = "quanlyhs")
public class LoginStudent implements java.io.Serializable {

	private LoginStudentId id;

	public LoginStudent() {
	}

	public LoginStudent(LoginStudentId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "username", column = @Column(name = "username", nullable = false, length = 100)),
			@AttributeOverride(name = "pass", column = @Column(name = "pass", nullable = false, length = 100)) })
	public LoginStudentId getId() {
		return this.id;
	}

	public void setId(LoginStudentId id) {
		this.id = id;
	}

}
