package QuanLy;
// Generated Jun 19, 2020, 1:40:23 PM by Hibernate Tools 3.5.0.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 18hcbCtt002 generated by hbm2java
 */
@Entity
@Table(name="18hcb_ctt002"
    ,catalog="quanlyhs"
)
public class lop18hcbCtt002  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer stt;
     private String mssv;
     private String hoTen;
     private String gioiTinh;
     private String cmnd;

    public lop18hcbCtt002() {
    }

    public lop18hcbCtt002(String mssv, String hoTen, String gioiTinh, String cmnd) {
       this.mssv = mssv;
       this.hoTen = hoTen;
       this.gioiTinh = gioiTinh;
       this.cmnd = cmnd;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="STT", unique=true, nullable=false)
    public Integer getStt() {
        return this.stt;
    }
    
    public void setStt(Integer stt) {
        this.stt = stt;
    }

    
    @Column(name="MSSV", nullable=false, length=100)
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }

    
    @Column(name="HoTen", nullable=false)
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }

    
    @Column(name="GioiTinh", nullable=false, length=100)
    public String getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(String gioiTinh) {
        this.gioiTinh = gioiTinh;
    }

    
    @Column(name="CMND", nullable=false, length=100)
    public String getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(String cmnd) {
        this.cmnd = cmnd;
    }




}
