package QuanLy;
// Generated Jun 19, 2020, 2:16:51 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Lop17hcb generated by hbm2java
 */
@Entity
@Table(name = "lop17hcb", catalog = "quanlyhs")
public class Lop17hcb implements java.io.Serializable {

	private String maLop;
	private int stt;
	private String mssv;
	private String hoTen;
	private String gioiTinh;
	private String cmnd;

	public Lop17hcb() {
	}

	public Lop17hcb(String maLop, int stt, String mssv, String hoTen, String gioiTinh, String cmnd) {
		this.maLop = maLop;
		this.stt = stt;
		this.mssv = mssv;
		this.hoTen = hoTen;
		this.gioiTinh = gioiTinh;
		this.cmnd = cmnd;
	}

	@Id

	@Column(name = "MaLop", unique = true, nullable = false, length = 100)
	public String getMaLop() {
		return this.maLop;
	}

	public void setMaLop(String maLop) {
		this.maLop = maLop;
	}

	@Column(name = "STT", nullable = false)
	public int getStt() {
		return this.stt;
	}

	public void setStt(int stt) {
		this.stt = stt;
	}

	@Column(name = "MSSV", nullable = false, length = 100)
	public String getMssv() {
		return this.mssv;
	}

	public void setMssv(String mssv) {
		this.mssv = mssv;
	}

	@Column(name = "HoTen", nullable = false)
	public String getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(String hoTen) {
		this.hoTen = hoTen;
	}

	@Column(name = "GioiTinh", nullable = false, length = 100)
	public String getGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(String gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	@Column(name = "CMND", nullable = false, length = 100)
	public String getCmnd() {
		return this.cmnd;
	}

	public void setCmnd(String cmnd) {
		this.cmnd = cmnd;
	}

}
