package QuanLy;
// Generated Jun 19, 2020, 2:16:51 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Lop18hcbId generated by hbm2java
 */
@Embeddable
public class Lop18hcbId implements java.io.Serializable {

	private int stt;
	private String mssv;
	private String hoTen;
	private String gioiTinh;
	private String cmnd;
	private String maLop;

	public Lop18hcbId() {
	}

	public Lop18hcbId(int stt, String mssv, String hoTen, String gioiTinh, String cmnd, String maLop) {
		this.stt = stt;
		this.mssv = mssv;
		this.hoTen = hoTen;
		this.gioiTinh = gioiTinh;
		this.cmnd = cmnd;
		this.maLop = maLop;
	}

	@Column(name = "STT", nullable = false)
	public int getStt() {
		return this.stt;
	}

	public void setStt(int stt) {
		this.stt = stt;
	}

	@Column(name = "MSSV", nullable = false, length = 100)
	public String getMssv() {
		return this.mssv;
	}

	public void setMssv(String mssv) {
		this.mssv = mssv;
	}

	@Column(name = "HoTen", nullable = false)
	public String getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(String hoTen) {
		this.hoTen = hoTen;
	}

	@Column(name = "GioiTinh", nullable = false, length = 100)
	public String getGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(String gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	@Column(name = "CMND", nullable = false, length = 100)
	public String getCmnd() {
		return this.cmnd;
	}

	public void setCmnd(String cmnd) {
		this.cmnd = cmnd;
	}

	@Column(name = "MaLop", nullable = false, length = 100)
	public String getMaLop() {
		return this.maLop;
	}

	public void setMaLop(String maLop) {
		this.maLop = maLop;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Lop18hcbId))
			return false;
		Lop18hcbId castOther = (Lop18hcbId) other;

		return (this.getStt() == castOther.getStt())
				&& ((this.getMssv() == castOther.getMssv()) || (this.getMssv() != null && castOther.getMssv() != null
						&& this.getMssv().equals(castOther.getMssv())))
				&& ((this.getHoTen() == castOther.getHoTen()) || (this.getHoTen() != null
						&& castOther.getHoTen() != null && this.getHoTen().equals(castOther.getHoTen())))
				&& ((this.getGioiTinh() == castOther.getGioiTinh()) || (this.getGioiTinh() != null
						&& castOther.getGioiTinh() != null && this.getGioiTinh().equals(castOther.getGioiTinh())))
				&& ((this.getCmnd() == castOther.getCmnd()) || (this.getCmnd() != null && castOther.getCmnd() != null
						&& this.getCmnd().equals(castOther.getCmnd())))
				&& ((this.getMaLop() == castOther.getMaLop()) || (this.getMaLop() != null
						&& castOther.getMaLop() != null && this.getMaLop().equals(castOther.getMaLop())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStt();
		result = 37 * result + (getMssv() == null ? 0 : this.getMssv().hashCode());
		result = 37 * result + (getHoTen() == null ? 0 : this.getHoTen().hashCode());
		result = 37 * result + (getGioiTinh() == null ? 0 : this.getGioiTinh().hashCode());
		result = 37 * result + (getCmnd() == null ? 0 : this.getCmnd().hashCode());
		result = 37 * result + (getMaLop() == null ? 0 : this.getMaLop().hashCode());
		return result;
	}

}
