package QuanLy;
// Generated Jun 19, 2020, 2:16:51 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NgayPhuckhaoId generated by hbm2java
 */
@Embeddable
public class NgayPhuckhaoId implements java.io.Serializable {

	private String maMon;
	private String ngayBd;
	private String ngayKt;

	public NgayPhuckhaoId() {
	}

	public NgayPhuckhaoId(String maMon, String ngayBd, String ngayKt) {
		this.maMon = maMon;
		this.ngayBd = ngayBd;
		this.ngayKt = ngayKt;
	}

	@Column(name = "MaMon", nullable = false, length = 100)
	public String getMaMon() {
		return this.maMon;
	}

	public void setMaMon(String maMon) {
		this.maMon = maMon;
	}

	@Column(name = "NgayBD", nullable = false, length = 100)
	public String getNgayBd() {
		return this.ngayBd;
	}

	public void setNgayBd(String ngayBd) {
		this.ngayBd = ngayBd;
	}

	@Column(name = "NgayKT", nullable = false, length = 100)
	public String getNgayKt() {
		return this.ngayKt;
	}

	public void setNgayKt(String ngayKt) {
		this.ngayKt = ngayKt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NgayPhuckhaoId))
			return false;
		NgayPhuckhaoId castOther = (NgayPhuckhaoId) other;

		return ((this.getMaMon() == castOther.getMaMon()) || (this.getMaMon() != null && castOther.getMaMon() != null
				&& this.getMaMon().equals(castOther.getMaMon())))
				&& ((this.getNgayBd() == castOther.getNgayBd()) || (this.getNgayBd() != null
						&& castOther.getNgayBd() != null && this.getNgayBd().equals(castOther.getNgayBd())))
				&& ((this.getNgayKt() == castOther.getNgayKt()) || (this.getNgayKt() != null
						&& castOther.getNgayKt() != null && this.getNgayKt().equals(castOther.getNgayKt())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMaMon() == null ? 0 : this.getMaMon().hashCode());
		result = 37 * result + (getNgayBd() == null ? 0 : this.getNgayBd().hashCode());
		result = 37 * result + (getNgayKt() == null ? 0 : this.getNgayKt().hashCode());
		return result;
	}

}
