package QuanLy;
// Generated Jun 19, 2020, 2:16:51 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NgayPhuckhao generated by hbm2java
 */
@Entity
@Table(name = "ngay_phuckhao", catalog = "quanlyhs")
public class NgayPhuckhao implements java.io.Serializable {

	private NgayPhuckhaoId id;

	public NgayPhuckhao() {
	}

	public NgayPhuckhao(NgayPhuckhaoId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "maMon", column = @Column(name = "MaMon", nullable = false, length = 100)),
			@AttributeOverride(name = "ngayBd", column = @Column(name = "NgayBD", nullable = false, length = 100)),
			@AttributeOverride(name = "ngayKt", column = @Column(name = "NgayKT", nullable = false, length = 100)) })
	public NgayPhuckhaoId getId() {
		return this.id;
	}

	public void setId(NgayPhuckhaoId id) {
		this.id = id;
	}

}
