package QuanLy;
// Generated Jun 19, 2020, 2:16:51 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ThongtinPhuckhao generated by hbm2java
 */
@Entity
@Table(name = "thongtin_phuckhao", catalog = "quanlyhs")
public class ThongtinPhuckhao implements java.io.Serializable {

	private ThongtinPhuckhaoId id;

	public ThongtinPhuckhao() {
	}

	public ThongtinPhuckhao(ThongtinPhuckhaoId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "mssv", column = @Column(name = "MSSV", nullable = false, length = 100)),
			@AttributeOverride(name = "hoTen", column = @Column(name = "HoTen", nullable = false)),
			@AttributeOverride(name = "maMon", column = @Column(name = "MaMon", nullable = false, length = 100)),
			@AttributeOverride(name = "cotDiem", column = @Column(name = "CotDiem", nullable = false, length = 100)),
			@AttributeOverride(name = "diemMuon", column = @Column(name = "DiemMuon", nullable = false, precision = 12, scale = 0)),
			@AttributeOverride(name = "liDo", column = @Column(name = "LiDo", nullable = false)),
			@AttributeOverride(name = "trangThai", column = @Column(name = "TrangThai", nullable = false)) })
	public ThongtinPhuckhaoId getId() {
		return this.id;
	}

	public void setId(ThongtinPhuckhaoId id) {
		this.id = id;
	}

}
