package QuanLy;
// Generated Jun 19, 2020, 2:16:51 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ThongtinPhuckhaoId generated by hbm2java
 */
@Embeddable
public class ThongtinPhuckhaoId implements java.io.Serializable {

	private String mssv;
	private String hoTen;
	private String maMon;
	private String cotDiem;
	private float diemMuon;
	private String liDo;
	private int trangThai;

	public ThongtinPhuckhaoId() {
	}

	public ThongtinPhuckhaoId(String mssv, String hoTen, String maMon, String cotDiem, float diemMuon, String liDo,
			int trangThai) {
		this.mssv = mssv;
		this.hoTen = hoTen;
		this.maMon = maMon;
		this.cotDiem = cotDiem;
		this.diemMuon = diemMuon;
		this.liDo = liDo;
		this.trangThai = trangThai;
	}

	@Column(name = "MSSV", nullable = false, length = 100)
	public String getMssv() {
		return this.mssv;
	}

	public void setMssv(String mssv) {
		this.mssv = mssv;
	}

	@Column(name = "HoTen", nullable = false)
	public String getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(String hoTen) {
		this.hoTen = hoTen;
	}

	@Column(name = "MaMon", nullable = false, length = 100)
	public String getMaMon() {
		return this.maMon;
	}

	public void setMaMon(String maMon) {
		this.maMon = maMon;
	}

	@Column(name = "CotDiem", nullable = false, length = 100)
	public String getCotDiem() {
		return this.cotDiem;
	}

	public void setCotDiem(String cotDiem) {
		this.cotDiem = cotDiem;
	}

	@Column(name = "DiemMuon", nullable = false, precision = 12, scale = 0)
	public float getDiemMuon() {
		return this.diemMuon;
	}

	public void setDiemMuon(float diemMuon) {
		this.diemMuon = diemMuon;
	}

	@Column(name = "LiDo", nullable = false)
	public String getLiDo() {
		return this.liDo;
	}

	public void setLiDo(String liDo) {
		this.liDo = liDo;
	}

	@Column(name = "TrangThai", nullable = false)
	public int getTrangThai() {
		return this.trangThai;
	}

	public void setTrangThai(int trangThai) {
		this.trangThai = trangThai;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ThongtinPhuckhaoId))
			return false;
		ThongtinPhuckhaoId castOther = (ThongtinPhuckhaoId) other;

		return ((this.getMssv() == castOther.getMssv()) || (this.getMssv() != null && castOther.getMssv() != null
				&& this.getMssv().equals(castOther.getMssv())))
				&& ((this.getHoTen() == castOther.getHoTen()) || (this.getHoTen() != null
						&& castOther.getHoTen() != null && this.getHoTen().equals(castOther.getHoTen())))
				&& ((this.getMaMon() == castOther.getMaMon()) || (this.getMaMon() != null
						&& castOther.getMaMon() != null && this.getMaMon().equals(castOther.getMaMon())))
				&& ((this.getCotDiem() == castOther.getCotDiem()) || (this.getCotDiem() != null
						&& castOther.getCotDiem() != null && this.getCotDiem().equals(castOther.getCotDiem())))
				&& (this.getDiemMuon() == castOther.getDiemMuon())
				&& ((this.getLiDo() == castOther.getLiDo()) || (this.getLiDo() != null && castOther.getLiDo() != null
						&& this.getLiDo().equals(castOther.getLiDo())))
				&& (this.getTrangThai() == castOther.getTrangThai());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMssv() == null ? 0 : this.getMssv().hashCode());
		result = 37 * result + (getHoTen() == null ? 0 : this.getHoTen().hashCode());
		result = 37 * result + (getMaMon() == null ? 0 : this.getMaMon().hashCode());
		result = 37 * result + (getCotDiem() == null ? 0 : this.getCotDiem().hashCode());
		result = 37 * result + (int) this.getDiemMuon();
		result = 37 * result + (getLiDo() == null ? 0 : this.getLiDo().hashCode());
		result = 37 * result + this.getTrangThai();
		return result;
	}

}
