package QuanLy;
// Generated Jun 19, 2020, 2:16:51 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tkb18hcb generated by hbm2java
 */
@Entity
@Table(name = "tkb_18hcb", catalog = "quanlyhs")
public class Tkb18hcb implements java.io.Serializable {

	private String maMon;
	private int stt;
	private String tenMon;
	private String phongHoc;
	private String maLop;

	public Tkb18hcb() {
	}

	public Tkb18hcb(String maMon, int stt, String tenMon, String phongHoc, String maLop) {
		this.maMon = maMon;
		this.stt = stt;
		this.tenMon = tenMon;
		this.phongHoc = phongHoc;
		this.maLop = maLop;
	}

	@Id

	@Column(name = "MaMon", unique = true, nullable = false, length = 100)
	public String getMaMon() {
		return this.maMon;
	}

	public void setMaMon(String maMon) {
		this.maMon = maMon;
	}

	@Column(name = "STT", nullable = false)
	public int getStt() {
		return this.stt;
	}

	public void setStt(int stt) {
		this.stt = stt;
	}

	@Column(name = "TenMon", nullable = false)
	public String getTenMon() {
		return this.tenMon;
	}

	public void setTenMon(String tenMon) {
		this.tenMon = tenMon;
	}

	@Column(name = "PhongHoc", nullable = false, length = 100)
	public String getPhongHoc() {
		return this.phongHoc;
	}

	public void setPhongHoc(String phongHoc) {
		this.phongHoc = phongHoc;
	}

	@Column(name = "MaLop", nullable = false, length = 100)
	public String getMaLop() {
		return this.maLop;
	}

	public void setMaLop(String maLop) {
		this.maLop = maLop;
	}

}
